build.gradle
src/main/java/wad/seoul_nolgoat/domain/store/Store.java
src/main/java/wad/seoul_nolgoat/domain/store/StoreRepositoryCustomImpl.java
src/main/java/wad/seoul_nolgoat/service/databaseSeeder/DatabaseSeederService.java
src/main/java/wad/seoul_nolgoat/service/search/SearchService.java
src/main/java/wad/seoul_nolgoat/service/search/dto/DistanceSortCombinationDto.java
src/main/java/wad/seoul_nolgoat/service/search/sort/SortService.java

기존 Store 엔터티의 위도 경도 
```java
private String lotAddress;
private String roadAddress;
```
수정된 Store 엔터티의 위도 경도 
```java
private Point location;
```
좌표가 동일할 때는 TMap API를 호출하지 않고 0 반환

상점의 위도 경도를 Point 자료형으로 저장하도록 수정

---

src/main/java/wad/seoul_nolgoat/domain/store/StoreCategory.java
src/main/java/wad/seoul_nolgoat/domain/store/StoreRepositoryCustom.java
src/main/java/wad/seoul_nolgoat/domain/store/StoreRepositoryCustomImpl.java
src/main/java/wad/seoul_nolgoat/service/search/SearchService.java
src/main/java/wad/seoul_nolgoat/service/search/filter/FilterService.java
src/main/java/wad/seoul_nolgoat/web/search/SearchController.java
src/main/java/wad/seoul_nolgoat/web/search/dto/request/PossibleCategoriesConditionDto.java

1) 주변 반경에 있는 카테고리(카카오) 문자열 가져오기
ex. `음식점 > 한식 > 해물,생선 > 장어` (예시로 하나의 카테고리 문자열만)
2) 카테고리 문자열 토큰화
ex. `한식` `해물,생선`
3) 관련된 모든 카테고리 반환
ex. `한식` `해물,생선` `해산물` `해물` `생선`

주어진 반경 내에 있는 상점의 카테고리 반환 기능 구현

---

.gitignore
build.gradle
src/main/java/wad/seoul_nolgoat/config/S3Config.java
src/main/java/wad/seoul_nolgoat/domain/review/Review.java
src/main/java/wad/seoul_nolgoat/domain/review/ReviewRepository.java
src/main/java/wad/seoul_nolgoat/domain/store/StoreRepository.java
src/main/java/wad/seoul_nolgoat/service/review/ReviewService.java
src/main/java/wad/seoul_nolgoat/service/s3/S3Service.java
src/main/java/wad/seoul_nolgoat/service/store/StoreService.java
src/main/java/wad/seoul_nolgoat/util/DateTimeUtil.java
src/main/java/wad/seoul_nolgoat/util/mapper/ReviewMapper.java
src/main/java/wad/seoul_nolgoat/util/mapper/UserMapper.java
src/main/java/wad/seoul_nolgoat/web/auth/dto/response/UserProfileDto.java
src/main/java/wad/seoul_nolgoat/web/review/ReviewController.java
src/main/java/wad/seoul_nolgoat/web/review/dto/request/ReviewSaveDto.java
src/main/java/wad/seoul_nolgoat/web/review/dto/request/ReviewUpdateDto.java
src/main/java/wad/seoul_nolgoat/web/review/dto/response/ReviewDetailsForStoreDto.java
src/main/java/wad/seoul_nolgoat/web/review/dto/response/ReviewDetailsForUserDto.java
src/main/java/wad/seoul_nolgoat/web/search/dto/request/SearchConditionDto.java
src/main/resources/application.yml

- 사용자가 첨부한 이미지를(MultipartFile) AWS S3에 저장
- S3에 저장한 이미지 링크를 DB 에 저장
- 이미지 링크를 통해 S3에 저장된 파일 삭제
- DB에 이미지 링크 삭제
카테고리 중 쉼표를 포함한 값이 있어서 기본 구분자인 쉼표를 사용하면 의도하지 않은 결과가 나온다. (ex. "고기,육류"라는 카테고리 하나를 컨트롤러가 받으면 categories에 "고기", "육류" 두개의 카테고리로 저장된다) 이를 해결하기 위해 프론트엔드에서 카테고리를 쉼표가 아닌 ; 로 구분해서 요청을 보낸다 (ex. "고기,육류;한식;중식"). 때문에 SearchConditionDto에서 카테고리를 받을 때 ;로 구분하여 받아야 한다.

Review 작성 시 이미지 업로드 기능, Store의 nolgoat 평점 업데이트 기능 구현

---

src/main/java/wad/seoul_nolgoat/domain/store/StoreCategory.java
src/main/java/wad/seoul_nolgoat/service/search/SearchService.java

-  특정 카테고리가 주어졌을 때, 그에 해당하는 대표 카테고리 Enum 상수 이름을 반환하는 메서드 구현
- `findPrimaryCategoryName`   
- 예외를 throw하지 않고 Optional로 반환한다
- 대표 카테고리를 모을 때 존재하지 않는 카테고리여도 예외를 throw 하지 않고 넘어가도록 수정 
- `SearchService / searchPossibleCategories 메서드 `
-  `findRelatedCategoryNames` ->  `findPrimaryCategoryName` 메서드로 수정
- Optional 사용
close #43

가능한 카테고리를 반환할 때 Enum 상수 이름을 반환하도록 수정

---

src/main/java/wad/seoul_nolgoat/auth/service/AuthService.java

- 존재 여부를 판단하는 것이 아니라, 토큰의 값을 비교하도록 수정
- Refresh 토큰
```java
if (Objects.equals(tokenService.getToken(key), refreshToken)) {
throw new ApiException(REFRESH_TOKEN_NOT_FOUND);
}
```
- Access 토큰
```java
if (Objects.equals(tokenService.getToken(key), accessToken)) {
throw new ApiException(ACCESS_TOKEN_BLACKLISTED);
}
```
- 잘못된 토큰 검증 로직을 수정했습니다.
close #46

잘못된 토큰 검증 로직 수정

---

build.gradle
src/main/java/wad/seoul_nolgoat/SeoulNolgoatApplication.java
src/main/java/wad/seoul_nolgoat/auth/AuthUrlManager.java
src/main/java/wad/seoul_nolgoat/auth/oauth2/CustomOAuth2UserService.java
src/main/java/wad/seoul_nolgoat/auth/oauth2/OAuth2AuthorizationRequestResolverImpl.java
src/main/java/wad/seoul_nolgoat/auth/oauth2/RedisOAuth2AuthorizedClientService.java
src/main/java/wad/seoul_nolgoat/auth/oauth2/client/GoogleClient.java
src/main/java/wad/seoul_nolgoat/auth/oauth2/client/KakaoApiClient.java
src/main/java/wad/seoul_nolgoat/auth/oauth2/client/KakaoAuthClient.java
src/main/java/wad/seoul_nolgoat/auth/oauth2/client/KakaoTokenResponse.java
src/main/java/wad/seoul_nolgoat/auth/oauth2/client/SocialClientService.java
src/main/java/wad/seoul_nolgoat/auth/oauth2/client/TokenResponse.java
src/main/java/wad/seoul_nolgoat/auth/oauth2/client/UnlinkResponse.java
src/main/java/wad/seoul_nolgoat/auth/service/AuthService.java
src/main/java/wad/seoul_nolgoat/auth/service/RedisTokenService.java
src/main/java/wad/seoul_nolgoat/auth/service/TokenService.java
src/main/java/wad/seoul_nolgoat/auth/web/AuthController.java
src/main/java/wad/seoul_nolgoat/config/SecurityConfig.java
src/main/java/wad/seoul_nolgoat/domain/user/User.java
src/main/java/wad/seoul_nolgoat/service/user/UserService.java
src/main/java/wad/seoul_nolgoat/web/admin/AdminController.java
src/main/java/wad/seoul_nolgoat/web/user/UserController.java

- **OpenFeign을 활용한 Social Client 인터페이스 구현** 
- KakaoAuthClient
- 토큰 재발급
- KakaoApiClient
- 계정 연결 해제
- GoogleClient
- 토큰 재발급
- 계정 연결 해제
- **OAuth2 관련 인터페이스 커스텀 구현**
- OAuth2AuthorizationRequestResolverImpl
- `Google` 로그인의 경우에는 `Refresh` 토큰을 발급받기 위해 특정 파라미터(`prompt`, `access_type`)를 추가해야 합니다.
- 이처럼, 분기 설정을 위해 `OAuth2AuthorizationRequestResolver`를 커스텀 구현했습니다.
- RedisOAuth2AuthorizedClientService
- 기본적으로 `OAuth2AuthorizedClient`는 `인메모리` 방식으로 관리됩니다.
- 저희는 토큰 관리만 필요하기 때문에, `Redis`를 활용해 OAuth2 토큰을 관리하도록 `OAuth2AuthorizedClientService`를 커스텀 구현했습니다.
- **회원 탈퇴 로직**
1. 캐시에 OAuth2 `Access` 토큰이 존재하는지 확인합니다.
2. 만약 기한이 만료되어 `Access` 토큰이 존재하지 않는다면, OAuth2 `Refresh` 토큰을 사용하여 `Access` 토큰을 재발급받습니다.
3. OAuth2 `Access` 토큰으로 계정 연결 해제를 신청합니다. 
4. 연결 해제에 성공하면, 캐시에서 OAuth2 `Refresh` 토큰을 삭제하고, 해당 유저의 `isDeleted` …

회원 탈퇴 시, 소셜 로그인 제공자와의 계정 연결 해제

---

src/main/java/wad/seoul_nolgoat/auth/AuthUrlManager.java

- **Notice, Inquiry 관련 URL을 올바르게 수정**
- `new AntPathRequestMatcher("/api/inquiries/{userId}", "POST")`
=> `new AntPathRequestMatcher("/api/inquiries", "POST")`
- `new AntPathRequestMatcher("/api/notices/{userId}", "POST")`
=> `new AntPathRequestMatcher("/api/notices", "POST")`
- **불필요한 URL 삭제**
- `new AntPathRequestMatcher("/api/notices/{noticeId}/views", "PUT")` 삭제
- 인증이 필요한 `URL` 모음을 올바르게 수정
close #53

AuthUrlManager 수정

---

src/main/java/wad/seoul_nolgoat/auth/oauth2/security/CustomOAuth2UserService.java
src/main/java/wad/seoul_nolgoat/auth/security/AuthenticationEntryPointImpl.java
src/main/java/wad/seoul_nolgoat/auth/service/AuthService.java
src/main/java/wad/seoul_nolgoat/auth/web/AuthController.java
src/main/java/wad/seoul_nolgoat/domain/bookmark/BookmarkRepository.java
src/main/java/wad/seoul_nolgoat/domain/store/StoreRepository.java
src/main/java/wad/seoul_nolgoat/exception/GlobalExceptionHandler.java
src/main/java/wad/seoul_nolgoat/exception/dto/response/ErrorResponse.java
src/main/java/wad/seoul_nolgoat/service/bookmark/BookmarkService.java
src/main/java/wad/seoul_nolgoat/service/databaseSeeder/DatabaseSeederService.java
src/main/java/wad/seoul_nolgoat/service/inquiry/InquiryService.java
src/main/java/wad/seoul_nolgoat/service/notice/NoticeService.java
src/main/java/wad/seoul_nolgoat/service/review/ReviewService.java
src/main/java/wad/seoul_nolgoat/service/search/filter/FilterService.java
src/main/java/wad/seoul_nolgoat/service/store/StoreService.java
src/main/java/wad/seoul_nolgoat/service/user/UserService.java
src/main/java/wad/seoul_nolgoat/web/inquiry/InquiryController.java
src/main/java/wad/seoul_nolgoat/web/notice/NoticeController.java
src/main/java/wad/seoul_nolgoat/web/review/ReviewController.java
src/main/java/wad/seoul_nolgoat/web/user/UserController.java

- **누락된 트랜잭션 적용 및 통일**
- `클래스` 단위에는 `@Transactional(readOnly = true)`를 적용합니다.
- `메서드` 단위에는 `변경`이 일어나는 로직에만 `@Transactional`을 적용합니다.
- **컨트롤러의 와일드카드 응답 타입 통일**
- `ResponseEntity<?>` 응답 타입을 `ResponseEntity<Void>`로 통일했습니다.
- `트랜잭션` 적용 방식 및 컨트롤러 `응답 타입` 통일
close #58

누락된 트랜잭션 적용 및 컨트롤러 응답 타입 통일

---

src/main/java/wad/seoul_nolgoat/service/search/sort/SortService.java

- **SortService**
- 인덱스가 올바르게 적용되도록 수정
```java
double baseTotalGrade = gradeCombinations.get(Math.min(9, gradeCombinations.size() - 1)).getTotalGrade();    
```
- 인덱스가 올바르게 적용되지 않아 `NullPointerException`이 발생하는 문제 해결
close #61

가게 조합 조회의 잘못된 로직 수정

---

src/main/java/wad/seoul_nolgoat/domain/store/StoreRepositoryCustomImpl.java
src/main/java/wad/seoul_nolgoat/service/search/dto/StoreForDistanceSortDto.java
src/main/java/wad/seoul_nolgoat/service/search/sort/SortService.java
src/main/java/wad/seoul_nolgoat/service/tMap/TMapService.java
src/main/java/wad/seoul_nolgoat/service/tMap/dto/WalkRouteInfoDto.java

- **조합 경우의 수 줄이기**
- 차수마다 기준이 되는 순번(`30번째`)의 거리 이하인 가게들만 가져오도록 수정했습니다.
- 기준 순번은 `강남역`과 `종로3가역`을 기준으로 설정했습니다.
- **총거리가 동일한 조합들이, 정해진 순서 때문에 결과에서 제외되던 문제 해결**
- 총거리별로 그룹화하고, 그룹 내에서는 순서를 무작위로 섞도록 했습니다.
거리 기준 조회 개선
close #63
- 기존에는 평점 기준 조회 시, 2번의 쿼리(기준 평점 조회 + 해당 평점 이상의 가게 조회)가 발생했으나, 이를 하나의 쿼리로 처리하도록 로직을 수정했습니다.

거리 순으로 가게 조합을 구성할 때, 필요한 전체 경우의 수 줄이기

---

src/main/java/wad/seoul_nolgoat/exception/ErrorCode.java
src/main/java/wad/seoul_nolgoat/exception/TMapException.java
src/main/java/wad/seoul_nolgoat/service/search/SearchService.java
src/main/java/wad/seoul_nolgoat/service/search/dto/DistanceSortCombinationDto.java
src/main/java/wad/seoul_nolgoat/service/search/sort/DistanceCalculator.java
src/main/java/wad/seoul_nolgoat/service/search/sort/SortService.java
src/main/java/wad/seoul_nolgoat/service/tMap/TMapService.java
src/main/java/wad/seoul_nolgoat/service/tMap/dto/WalkRouteInfoDto.java
src/main/java/wad/seoul_nolgoat/util/mapper/CombinationMapper.java

- **TMap 도보 경로 계산 API 사용 횟수 초과 처리**
- `TMap` API를 모두 사용하면, 직선거리 계산으로 자동 대체하도록 수정했습니다.
- **TMap 관련 커스텀 예외 추가**
- `TMap` API 에러를 별도로 처리할 수 있도록 `TMapException`을 구현했습니다.
- 예외는 기존에 있는 `ApiException`을 상속하여 공통 에러 처리 흐름을 유지했습니다.
- `TMap` API 사용 횟수 초과 시, 직선 거리 계산 로직 추가
- `TMapException` 도입으로 `TMap` 에러 관리 개선
close #65

TMap API 일일 호출 제한 초과 시, 대체 로직 구현

---

src/main/java/wad/seoul_nolgoat/service/search/sort/SortService.java

- **SortService**
- 총거리 기준으로 정렬 후, 같은 결과끼리는 그룹화하고, 그룹 내 항목들을 무작위로 섞는 과정에서 오름차순 정렬이 제대로 적용되도록 수정했습니다.
- 총거리 기준으로 조합 조회 시, 오름차순 정렬이 적용되지 않는 문제 해결
close #72
- `ApiException`을 `TMapException`으로 변경하여 TMap API에서 발생하는 예외를 정확하게 처리하도록 수정했습니다.

총거리 기준으로 조합 조회 시, 오름차순 정렬이 적용되지 않는 문제 해결

---

src/main/java/wad/seoul_nolgoat/config/SwaggerConfig.java

- **SwaggerConfig**
- `@OpenAPIDefinition`에 `servers = @Server(url = "https://server.nolgoat.site")`를 추가하여 Swagger UI에서 API 테스트 시 발생하는 `CORS` 문제를 해결했습니다.
- Swagger UI API의 기본 서버 URL을  `HTTPS`로 설정하여 `CORS` 문제 해결
close #73

Swagger UI에서 API 테스트 시 발생하는 CORS 문제 해결

---

src/main/java/wad/seoul_nolgoat/service/search/SearchService.java

SearchService의 searchPossibleCategories 메서드에서 Store Type으로 구분하여 토큰화하도록 수정하려고 합니다.
- RESTAURANT -> 카테고리 토큰화 하여 Set에 추가
- CAFE, PCROOM, KARAOKE, BILLIARD -> Store Type 자체를 Set에 추가 
Store Type으로 구분하여 토큰화하도록 수정하여, 가능한 카테고리에 놀거리 항목이 나오지 않는 오류 해결
close #76

fix: 가능한 카테고리에 놀거리 항목이 나오지 않는 오류 해결

---

src/main/java/wad/seoul_nolgoat/domain/store/Store.java
src/main/java/wad/seoul_nolgoat/domain/store/StoreRepository.java
src/main/java/wad/seoul_nolgoat/domain/store/StoreRepositoryCustom.java
src/main/java/wad/seoul_nolgoat/domain/store/StoreRepositoryCustomImpl.java
src/main/java/wad/seoul_nolgoat/domain/user/UserRepository.java
src/main/java/wad/seoul_nolgoat/service/bookmark/BookmarkService.java
src/main/java/wad/seoul_nolgoat/service/review/ReviewService.java
src/main/java/wad/seoul_nolgoat/service/store/StoreService.java
src/main/java/wad/seoul_nolgoat/util/mapper/StoreMapper.java
src/main/java/wad/seoul_nolgoat/web/review/ReviewController.java
src/main/java/wad/seoul_nolgoat/web/store/StoreController.java
src/main/java/wad/seoul_nolgoat/web/user/UserController.java

- **가게 단건 조회**
- `가게`, `리뷰`, `유저` 정보를 하나의 쿼리로 조회할 수 있도록 조인 로직을 개선했습니다.
- **리뷰의 평점 반영 로직 개선**
- 리뷰 `작성`, `수정`, `삭제` 시, 가게의 평균 평점에 반영하는 로직에서 불필요한 쿼리를 없앴습니다.
- **UserController 엔드포인트 수정**
- `UserId`를 통해 `리뷰` 및 `북마크` 목록을 가져오는 로직을 `유저` 도메인에 맞게 변경했습니다.
- 가게 단건 조회 시, 하나의 쿼리만 실행되도록 수정
- 리뷰 `작성`, `수정`, `삭제` 시, 가게 평균 평점 반영 로직 개선 (불필요한 쿼리 제거)
- `User` 도메인에 맞는 엔드포인트 구조로 변경
close #85

Store 관련 로직의 전반적인 개선

---

src/main/java/wad/seoul_nolgoat/domain/bookmark/BookmarkRepository.java
src/main/java/wad/seoul_nolgoat/domain/bookmark/BookmarkRepositoryCustom.java
src/main/java/wad/seoul_nolgoat/domain/bookmark/BookmarkRepositoryCustomImpl.java
src/main/java/wad/seoul_nolgoat/domain/review/ReviewRepository.java
src/main/java/wad/seoul_nolgoat/domain/review/ReviewRepositoryCustom.java
src/main/java/wad/seoul_nolgoat/domain/review/ReviewRepositoryCustomImpl.java
src/main/java/wad/seoul_nolgoat/service/bookmark/BookmarkService.java
src/main/java/wad/seoul_nolgoat/service/review/ReviewService.java
src/main/java/wad/seoul_nolgoat/util/mapper/ReviewMapper.java
src/main/java/wad/seoul_nolgoat/util/mapper/StoreMapper.java
src/main/java/wad/seoul_nolgoat/web/bookmark/dto/response/StoreForBookmarkDto.java
src/main/java/wad/seoul_nolgoat/web/review/dto/response/ReviewDetailsForUserDto.java
src/main/java/wad/seoul_nolgoat/web/store/dto/response/StoreForBookmarkDto.java
src/main/java/wad/seoul_nolgoat/web/user/UserController.java

- 유저 ID를 통한 리뷰 목록 조회 기능을 로그인 유저의 리뷰 목록 조회로 수정했습니다.
- 유저 ID를 통한 북마크 목록 조회 기능을 로그인 유저의 북마크 목록 조회로 수정했습니다.
- 기존의 리뷰 및 북마크 목록 조회를 내가 작성한 리뷰와 내가 추가한 북마크로 수정
close #88

유저 ID를 통한 리뷰 및 북마크 목록 조회 기능 수정

---

src/main/java/wad/seoul_nolgoat/auth/oauth2/security/CustomOAuth2UserService.java
src/main/java/wad/seoul_nolgoat/auth/security/AuthFilter.java
src/main/java/wad/seoul_nolgoat/auth/security/AuthenticationEntryPointImpl.java
src/main/java/wad/seoul_nolgoat/auth/service/AuthService.java
src/main/java/wad/seoul_nolgoat/domain/party/Party.java
src/main/java/wad/seoul_nolgoat/domain/store/StoreCategory.java
src/main/java/wad/seoul_nolgoat/exception/ApiException.java
src/main/java/wad/seoul_nolgoat/exception/ApplicationException.java
src/main/java/wad/seoul_nolgoat/exception/ErrorCode.java
src/main/java/wad/seoul_nolgoat/exception/GlobalExceptionHandler.java
src/main/java/wad/seoul_nolgoat/exception/TMapException.java
src/main/java/wad/seoul_nolgoat/service/bookmark/BookmarkService.java
src/main/java/wad/seoul_nolgoat/service/inquiry/InquiryService.java
src/main/java/wad/seoul_nolgoat/service/kakaoMap/KakaoMapService.java
src/main/java/wad/seoul_nolgoat/service/mail/MailService.java
src/main/java/wad/seoul_nolgoat/service/notice/NoticeService.java
src/main/java/wad/seoul_nolgoat/service/party/PartyService.java
src/main/java/wad/seoul_nolgoat/service/review/ReviewService.java
src/main/java/wad/seoul_nolgoat/service/s3/S3Service.java
src/main/java/wad/seoul_nolgoat/service/search/SearchService.java
src/main/java/wad/seoul_nolgoat/service/store/StoreService.java
src/main/java/wad/seoul_nolgoat/service/tMap/TMapService.java
src/main/java/wad/seoul_nolgoat/service/user/UserService.java
src/test/java/wad/seoul_nolgoat/service/InquiryServiceTest.java
src/test/java/wad/seoul_nolgoat/service/NoticeServiceTest.java
src/test/java/wad/seoul_nolgoat/service/PartyServiceTest.java

- 예외 변환 시, 기존 예외를 포함하도록 수정했습니다.
- 예외 변환 시, 기존 예외를 포함하도록 수정
- 커스텀 예외명 `ApiException`을 `ApplicationException`으로 수정
- `TMapException`을 `ApplicationException`과 상속 관계가 아닌 별도의 커스텀 예외로 분리
close #95

예외 변환 시, 기존 예외를 포함하도록 수정

---

src/main/java/wad/seoul_nolgoat/domain/store/Store.java

상점의 리뷰가 하나 있을 때 삭제되지 않는 오류를 해결하려고 합니다.
`this.nolgoatAverageGrade = ((previousNolgoatAverageGrade * reviewCount) - nolgoatGrade) / (reviewCount - 1);`
reviewCount가 1일 때 분모가 0이 되어 오류 발생
close #100

상점의 리뷰가 하나 있을 때 삭제되지 않는 오류 해결 

---

.github/workflows/deploy.yml

- 스크립트에 gradlew 파일 실행 권한 설정 명령어를 추가합니다.
- 배포 스크립트에 파일 권한 설정 추가
close #108

배포 스크립트에 파일 권한 설정 추가

---

.github/workflows/build-test.yml

- 기존 워크플로우 파일을 분할하여 하나는 PR 작성 시 확인용으로, 다른 하나는 main 브랜치 배포용으로 분리했습니다.
- 워크플로우 파일 분할
close #112

워크플로우 파일 분할

---

src/main/java/wad/seoul_nolgoat/auth/util/AuthUrlManager.java
src/main/java/wad/seoul_nolgoat/config/SecurityConfig.java
src/main/java/wad/seoul_nolgoat/web/comment/CommentController.java
src/main/java/wad/seoul_nolgoat/web/inquiry/InquiryController.java
src/main/java/wad/seoul_nolgoat/web/notice/NoticeController.java
src/main/java/wad/seoul_nolgoat/web/party/PartyController.java
src/main/java/wad/seoul_nolgoat/web/review/ReviewController.java

- 서버 공격 시도 URL 차단을 위해 애플리케이션 엔드포인트 이외의 모든 요청을 거부하도록 Security 설정을 변경했습니다.
- 서버 공격 시도 URL 차단을 위한 Security 설정 변경
close #126

서버 공격 시도 URL 차단을 위한 Security 설정 변경

---

src/main/java/wad/seoul_nolgoat/domain/store/StoreRepositoryCustomImpl.java

- 기존 코드
```java
@Override
public List<StoreForGradeSortDto> findByRadiusRangeAndCategoryForKakaoGradeSort(
CoordinateDto startCoordinate,
double radiusRange,
String category
) {
List<StoreForGradeSortDto> result = createBaseQueryForKakaoGradeSorted()
.where(
buildRangeAndCategoryCondition(
startCoordinate,
radiusRange,
category
)
)
.orderBy(store.kakaoAverageGrade.desc())
.fetch();
int resultCount = Math.min(GRADE_SORT_MAX_RESULT_COUNT, result.size());
double baseKakaoAverageGrade = result.get(resultCount - 1).getKakaoAverageGrade();
return result.stream()
.filter(store -> store.getKakaoAverageGrade() >= baseKakaoAverageGrade)
.toList();
}
```
- 수정된 코드
```java
@Override
public List<StoreForGradeSortDto> findByRadiusRangeAndCategoryForKakaoGradeSort(
CoordinateDto startCoordinate,
double …
```

가게 목록 조회 성능 개선

---

src/main/java/wad/seoul_nolgoat/domain/party/PartyRepositoryCustomImpl.java
src/main/java/wad/seoul_nolgoat/domain/partyuser/PartyUserRepositoryCustomImpl.java
src/main/java/wad/seoul_nolgoat/util/DateTimeUtil.java
src/main/java/wad/seoul_nolgoat/web/party/request/PartySaveDto.java
src/main/java/wad/seoul_nolgoat/web/party/request/PartyUpdateDto.java
src/main/java/wad/seoul_nolgoat/web/party/response/PartyDetailsDto.java
src/main/java/wad/seoul_nolgoat/web/party/response/PartyDetailsForListDto.java

- 파티 응답 DTO를 수정했습니다.
- 올바른 유효성 검증 어노테이션을 적용했습니다.  
- 파티 조회 DTO의 createdDateAgo 필드를 문자열로 반환하도록 수정
- 문자열이 아닌 변수에는 @NotBlank 대신 @NotNull을 적용 
close #136

파티 응답 DTO 수정 및 어노테이션 오류 해결 

---

src/test/java/wad/seoul_nolgoat/service/PartyServiceTest.java

- 모임 일이 지난 파티는 자동 마감되는 로직을 테스트에 반영
- 모임 일이 지난 파티는 자동 마감되는 로직을 테스트에 반영
close #138

추가한 로직이 반영되지 않은 테스트 수정

---

src/main/java/wad/seoul_nolgoat/auth/security/AuthFilter.java
src/main/java/wad/seoul_nolgoat/auth/security/AuthUrlManager.java
src/main/java/wad/seoul_nolgoat/config/SecurityConfig.java

- AuthUrlManager 수정
- 빈으로 등록 및 의존성 주입
- 폴더 구조 변경 (`/auth/util` -> `/auth/security`)
- SecurityConfig 수정
- 토큰 재발급 요청은 `permitAll()` 처리
- Access 토큰 재발급 요청 URL은 인증이 필요 없도록 설정 수정
close #143

Access 토큰 재발급 요청 URL은 인증이 필요 없도록 설정 수정

---

src/main/java/wad/seoul_nolgoat/domain/party/PartyRepositoryCustomImpl.java
src/main/java/wad/seoul_nolgoat/web/party/request/PartySaveDto.java
src/main/java/wad/seoul_nolgoat/web/party/request/PartyUpdateDto.java

- 파티 요청 DTO 수정
- 제목 글자 제한을 40자로 수정
- 모임 일 유효성 검증 통일 (`@FutureOrPresent`)
- 파티 목록 조회 시, 모임 일 기준 정렬은 오름차순으로 수정
- 파티 생성 유효성 검사 기준 및 파티 목록 조회 정렬 방식 수정
close #145

파티 생성 유효성 검사 기준 및 파티 목록 조회 정렬 방식 수정

---

src/main/java/wad/seoul_nolgoat/domain/comment/Comment.java
src/main/java/wad/seoul_nolgoat/domain/comment/CommentRepositoryCustomImpl.java
src/main/java/wad/seoul_nolgoat/service/comment/CommentService.java
src/main/java/wad/seoul_nolgoat/web/comment/dto/response/CommentDetailsForPartyDto.java
src/main/java/wad/seoul_nolgoat/web/comment/dto/response/CommentDetailsForUserDto.java

- 파티 댓글 삭제를 Soft Delete 방식으로 수정했습니다. 
- isDeleted 필드 추가  
- 파티 댓글 삭제 방식 수정 
close #154

파티 댓글 삭제를 Soft Delete로 수정 

---

src/main/java/wad/seoul_nolgoat/domain/comment/Comment.java
src/main/java/wad/seoul_nolgoat/domain/comment/CommentRepositoryCustomImpl.java
src/main/java/wad/seoul_nolgoat/service/comment/CommentService.java
src/main/java/wad/seoul_nolgoat/web/comment/dto/response/CommentDetailsForPartyDto.java
src/main/java/wad/seoul_nolgoat/web/comment/dto/response/CommentDetailsForUserDto.java

- Comment 엔티티 클래스 스펙 수정
- Soft Delete 적용을 위해 `isDeleted` 필드 추가 (응답 DTO에도 반영)
- 조회 시, 삭제 여부를 판단하여 `isDeleted`가 true면 내용을 '삭제된 댓글입니다'로 변환
- 2차 배포
close #

[Release] 2차 배포
