Seoul-NolGoat/be-seoul-nolgoat

- src/main/java/wad/seoul_nolgoat/domain/BaseTimeEntity.java
- src/main/java/wad/seoul_nolgoat/domain/bookmark/Bookmark.java
- src/main/java/wad/seoul_nolgoat/domain/bookmark/BookmarkRepository.java
- src/main/java/wad/seoul_nolgoat/domain/review/Review.java
- src/main/java/wad/seoul_nolgoat/domain/review/ReviewRepository.java
- src/main/java/wad/seoul_nolgoat/domain/store/Store.java
- src/main/java/wad/seoul_nolgoat/domain/store/StoreRepository.java
- src/main/java/wad/seoul_nolgoat/domain/store/Type.java
- src/main/java/wad/seoul_nolgoat/domain/user/LoginType.java
- src/main/java/wad/seoul_nolgoat/domain/user/User.java
- src/main/java/wad/seoul_nolgoat/domain/user/UserRepository.java
- src/main/java/wad/seoul_nolgoat/service/bookmark/BookmarkService.java
- src/main/java/wad/seoul_nolgoat/service/review/ReviewService.java
- src/main/java/wad/seoul_nolgoat/service/store/StoreService.java
- src/main/java/wad/seoul_nolgoat/service/user/UserService.java
- src/main/java/wad/seoul_nolgoat/web/bookmark/BookmarkController.java
- src/main/java/wad/seoul_nolgoat/web/review/ReviewController.java
- src/main/java/wad/seoul_nolgoat/web/review/dto/request/ReviewSave.java
- src/main/java/wad/seoul_nolgoat/web/review/dto/response/ReviewResponse.java
- src/main/java/wad/seoul_nolgoat/web/store/StoreController.java
- src/main/java/wad/seoul_nolgoat/web/store/dto/request/StoreSave.java
- src/main/java/wad/seoul_nolgoat/web/store/dto/response/StoreResponse.java
- src/main/java/wad/seoul_nolgoat/web/user/UserController.java
- src/main/java/wad/seoul_nolgoat/web/user/dto/request/UserSave.java
- src/main/java/wad/seoul_nolgoat/web/user/dto/response/UserResponse.java
- 엔터티 클래스 구현 및 연관관계 설정
- User
- Store
- Review
- Bookmark
- 디렉토리 구조 구현
- domain
- service
- web
> 엔터티 정의, 연관관계 설정 및 디렉토리 구조 구현

- .gitignore
- build.gradle
- src/main/java/wad/seoul_nolgoat/SeoulNolgoatApplication.java
- src/main/java/wad/seoul_nolgoat/domain/BaseTimeEntity.java
- src/main/java/wad/seoul_nolgoat/domain/bookmark/Bookmark.java
- src/main/java/wad/seoul_nolgoat/domain/review/Review.java
- src/main/java/wad/seoul_nolgoat/domain/store/Store.java
- src/main/java/wad/seoul_nolgoat/domain/store/StoreType.java
- src/main/java/wad/seoul_nolgoat/domain/user/User.java
- src/main/java/wad/seoul_nolgoat/service/databaseSeeder/DatabaseSeederService.java
- src/main/java/wad/seoul_nolgoat/service/kakaoMap/KakaoMapService.java
- src/main/java/wad/seoul_nolgoat/service/kakaoMap/dto/CoordinateDto.java
- src/main/java/wad/seoul_nolgoat/service/kakaoMap/dto/StoreAdditionalInfoDto.java
- src/main/java/wad/seoul_nolgoat/service/seoulStore/SeoulStoreService.java
- src/main/java/wad/seoul_nolgoat/web/databaseSeeder/DatabaseSeederController.java
- src/main/resources/application.yml
KakaoMapService
- 위도 경도 반환 기능
- Store 추가 정보 반환 기능
- 카카오 평점 반환 기능
SeoulStoreService
- 서울시 Store의 기본 정보 반환 기능
DatabaseSeederService
- KakaoMapService, SeoulStoreService를 통해 Store 정보를 모두 받아온 뒤 DB에 저장
> 초기 Store 데이터 DB에 넣는 기능 구현

- src/main/java/wad/seoul_nolgoat/domain/review/Review.java
- src/main/java/wad/seoul_nolgoat/domain/review/ReviewRepository.java
- src/main/java/wad/seoul_nolgoat/domain/store/Store.java
- src/main/java/wad/seoul_nolgoat/domain/user/User.java
- src/main/java/wad/seoul_nolgoat/service/review/ReviewService.java
- src/main/java/wad/seoul_nolgoat/service/store/StoreService.java
- src/main/java/wad/seoul_nolgoat/service/store/dto/StoreUpdateDto.java
- src/main/java/wad/seoul_nolgoat/util/mapper/ReviewMapper.java
- src/main/java/wad/seoul_nolgoat/util/mapper/StoreMapper.java
- src/main/java/wad/seoul_nolgoat/web/review/ReviewController.java
- src/main/java/wad/seoul_nolgoat/web/review/dto/response/ReviewDetailsForStoreDto.java
- src/main/java/wad/seoul_nolgoat/web/review/dto/response/ReviewDetailsForUserDto.java
- src/main/java/wad/seoul_nolgoat/web/store/StoreController.java
- src/main/java/wad/seoul_nolgoat/web/store/dto/response/StoreDetailsDto.java
- src/main/java/wad/seoul_nolgoat/web/store/dto/response/StoreResponse.java
- Store
- storeId로 단건 조회
Store 저장, 업데이트, 삭제 기능은 DatabaseSeeder를 통해 이루어지기 때문에 별도 API가 존재하지 않습니다.
> 엔터티(Store) 기본 CRUD 구현

- src/main/java/wad/seoul_nolgoat/config/WebConfig.java
- src/main/java/wad/seoul_nolgoat/service/databaseSeeder/DatabaseSeederService.java
- src/main/java/wad/seoul_nolgoat/service/kakaoMap/KakaoMapService.java
- src/main/java/wad/seoul_nolgoat/web/kakaoMap/KakaoMapController.java
- `fetchRoadAddress` : 좌표(위도, 경도)를 도로명 주소로 변경
- `fetchLotAddress` : 좌표(위도, 경도)를 지번 주소로 변경
> 좌표(위도, 경도)를 주소로 변환하는 기능 구현

- src/main/java/wad/seoul_nolgoat/domain/store/StoreRepositoryCustomImpl.java
- src/main/java/wad/seoul_nolgoat/service/search/SearchService.java
- src/main/java/wad/seoul_nolgoat/service/search/dto/StoreForDistanceSortDto.java
- src/main/java/wad/seoul_nolgoat/service/search/dto/StoreForGradeSortDto.java
- src/main/java/wad/seoul_nolgoat/service/search/sort/SortService.java
- src/main/java/wad/seoul_nolgoat/service/tMap/TMapService.java
- src/main/java/wad/seoul_nolgoat/util/mapper/CombinationMapper.java
- src/main/java/wad/seoul_nolgoat/util/mapper/StoreMapper.java
- src/main/java/wad/seoul_nolgoat/web/search/dto/response/CombinationDto.java
- src/main/java/wad/seoul_nolgoat/web/store/dto/response/StoreForCombinationDto.java
**StoreRepositoryCustomImpl**
- 반환 Store 정보에 평점 정보 추가
**CombinationDto**
- walkRouteInfoDto 변수 추가
**fetchFullPathWalkRouteInfo**
- SortService 클래스에서 TMapService 클래스로 이동
- Sort보다는 TMap에 관련된 메서드인 것 같다
- SortService 이외에 SearchService에서도 필요하다
**SearchService**
- fetchWalkRouteInfoForCombinationDto 메서드 구현
- 평점 조건으로 반환 된 List<CombinationDto>의 walkRouteInfoDto 값 계산 후 setter을 통해 값을 넣어준다
> 경로 검색 결과에 상점 정보 추가

- src/main/java/wad/seoul_nolgoat/domain/bookmark/BookmarkRepository.java
- src/main/java/wad/seoul_nolgoat/service/bookmark/BookmarkService.java
- src/main/java/wad/seoul_nolgoat/util/mapper/StoreMapper.java
- src/main/java/wad/seoul_nolgoat/web/bookmark/BookmarkController.java
- src/main/java/wad/seoul_nolgoat/web/store/StoreController.java
- src/main/java/wad/seoul_nolgoat/web/store/dto/response/StoreForBookmarkDto.java
- POST `/api/bookmarks/{userId}/{storeId}` 북마크 생성
- DELETE `/api/bookmarks/{userId}/{storeId}` 북마크 삭제
- GET `/api/bookmarks/{userId}/{storeId}` 주어진 userId, storeId에 맞는 북마크가 존재하는지 반환 (true / false)
- GET `/api/stores/bookmarked/{userId}` 주어진 userId가 북마크한 Store들의 정보를 반환
> Bookmark CRUD 구현

- src/main/java/wad/seoul_nolgoat/domain/store/StoreRepositoryCustom.java
- src/main/java/wad/seoul_nolgoat/domain/store/StoreRepositoryCustomImpl.java
- src/main/java/wad/seoul_nolgoat/domain/store/StoreType.java
- src/main/java/wad/seoul_nolgoat/service/search/SearchService.java
- src/main/java/wad/seoul_nolgoat/service/search/dto/StoreForPossibleCategoriesDto.java
- src/main/java/wad/seoul_nolgoat/service/search/filter/FilterService.java
- src/main/java/wad/seoul_nolgoat/web/search/dto/request/SearchConditionDto.java
- store type이 RESTAURANT 일 때
- 주어진 카테고리로 search
-  store type이 RESTAURANT 아닐 때 (CAFE, KARAOKE, PCROOM, PCROOM)
- 주어진 store type에 해당하는 상점들로  search
> RESTAURANT 이외의 store type 검색 기능 구현

- src/main/java/wad/seoul_nolgoat/domain/inquiry/Inquiry.java
- src/main/java/wad/seoul_nolgoat/domain/inquiry/InquiryRepository.java
- src/main/java/wad/seoul_nolgoat/exception/ErrorCode.java
- src/main/java/wad/seoul_nolgoat/exception/duplicate/ReviewDuplicateException.java
- src/main/java/wad/seoul_nolgoat/exception/notfound/InquiryNotFoundException.java
- src/main/java/wad/seoul_nolgoat/service/inquiry/InquiryService.java
- src/main/java/wad/seoul_nolgoat/service/review/ReviewService.java
- src/main/java/wad/seoul_nolgoat/util/mapper/InquiryMapper.java
- src/main/java/wad/seoul_nolgoat/web/exception/GlobalExceptionHandler.java
- src/main/java/wad/seoul_nolgoat/web/inquiry/InquiryController.java
- src/main/java/wad/seoul_nolgoat/web/inquiry/dto/request/InquirySaveDto.java
- src/main/java/wad/seoul_nolgoat/web/inquiry/dto/request/InquiryUpdateDto.java
- src/main/java/wad/seoul_nolgoat/web/inquiry/dto/response/InquiryDetailsDto.java
- src/main/java/wad/seoul_nolgoat/web/inquiry/dto/response/InquiryListDto.java
- POST `/api/inquiries/{userId}` Inquiry 생성
- GET `/api/inquiries/{inquiryId}` Inquiry 상세 반환 
- GET `/api/inquiries` 전체 Inquiry 목록 반환 
- PUT `/api/inquiries/{inquiryId}` Inquiry 업데이트
- DELETE `/api/inquiries/{inquiryId}` Inquiry 삭제
> Inquiry CRUD 구현

- src/main/java/wad/seoul_nolgoat/domain/notice/Notice.java
- src/main/java/wad/seoul_nolgoat/domain/notice/NoticeRepository.java
- src/main/java/wad/seoul_nolgoat/exception/ErrorCode.java
- src/main/java/wad/seoul_nolgoat/exception/notfound/NoticeNotFoundException.java
- src/main/java/wad/seoul_nolgoat/service/notice/NoticeService.java
- src/main/java/wad/seoul_nolgoat/util/mapper/NoticeMapper.java
- src/main/java/wad/seoul_nolgoat/web/exception/GlobalExceptionHandler.java
- src/main/java/wad/seoul_nolgoat/web/notice/NoticeController.java
- src/main/java/wad/seoul_nolgoat/web/notice/dto/request/NoticeSaveDto.java
- src/main/java/wad/seoul_nolgoat/web/notice/dto/request/NoticeUpdateDto.java
- src/main/java/wad/seoul_nolgoat/web/notice/dto/response/NoticeDetailsDto.java
- src/main/java/wad/seoul_nolgoat/web/notice/dto/response/NoticeListDto.java
- POST `/api/notices/{userId}` Notice생성
- GET `/api/notices/{noticeId}` Notice상세 반환
- GET `/api/notices`전체 Notice 목록 반환
- PUT `/api/notices/{noticeId}` Notice 업데이트
- DELETE `/api/notices/{noticeId}` Notice 삭제
- PUT `/api/notices/{noticeId}/views` Notice 조회수 증가
> Notice CRUD 구현

- src/main/java/wad/seoul_nolgoat/auth/service/AuthService.java
- `Refresh` 토큰 검증 로직 수정
```java
if (!Objects.equals(tokenService.getToken(key), refreshToken)) {
throw new ApiException(REFRESH_TOKEN_NOT_FOUND);
}
```
- `Refresh` 토큰 검증 로직 수정
close #48
> Refresh 토큰 검증 로직 수정

- build.gradle
- src/main/java/wad/seoul_nolgoat/auth/web/AuthController.java
- src/main/java/wad/seoul_nolgoat/config/SwaggerConfig.java
- src/main/java/wad/seoul_nolgoat/web/admin/AdminController.java
- src/main/java/wad/seoul_nolgoat/web/bookmark/BookmarkController.java
- src/main/java/wad/seoul_nolgoat/web/databaseSeeder/DatabaseSeederController.java
- src/main/java/wad/seoul_nolgoat/web/inquiry/InquiryController.java
- src/main/java/wad/seoul_nolgoat/web/kakaoMap/KakaoMapController.java
- src/main/java/wad/seoul_nolgoat/web/notice/NoticeController.java
- src/main/java/wad/seoul_nolgoat/web/party/PartyController.java
- src/main/java/wad/seoul_nolgoat/web/review/ReviewController.java
- src/main/java/wad/seoul_nolgoat/web/search/SearchController.java
- src/main/java/wad/seoul_nolgoat/web/store/StoreController.java
- src/main/java/wad/seoul_nolgoat/web/user/UserController.java
- `Swagger` 적용
- `Swagger` 적용
close #57
> Swagger 적용

- src/main/java/wad/seoul_nolgoat/domain/store/StoreRepositoryCustomImpl.java
- **StoreRepositoryCustomImpl**
- 불필요한 `distinct` 키워드 삭제
- 불필요한 `distinct` 삭제
close #70
> 불필요한 distinct 삭제

- src/main/java/wad/seoul_nolgoat/domain/bookmark/BookmarkRepository.java
- src/main/java/wad/seoul_nolgoat/exception/ErrorCode.java
- src/main/java/wad/seoul_nolgoat/service/bookmark/BookmarkService.java
- src/main/java/wad/seoul_nolgoat/service/review/ReviewService.java
- src/main/java/wad/seoul_nolgoat/web/bookmark/BookmarkController.java
- src/main/java/wad/seoul_nolgoat/web/review/ReviewController.java
- `북마크` `삭제` 요청에 대해 본인 검증 로직을 추가했습니다.
- `리뷰` `삭제` 요청에 대해 본인 검증 로직을 추가했습니다.
- `북마크` 및 `리뷰` `삭제` 요청에 대해 본인 검증 로직 추가
close #79
> 북마크 및 리뷰 삭제 요청에 대해 본인 검증 로직 추가

- src/main/java/wad/seoul_nolgoat/auth/util/AuthUrlManager.java
- **AuthUrlManager**
- `/api/auths/me`를 `/api/users/me`로 수정했습니다.
- API URL 변경에 따른 `AuthUrlManager` 수정
close #83
> API URL 변경 사항 반영

- src/main/java/wad/seoul_nolgoat/auth/util/AuthUrlManager.java
- src/main/java/wad/seoul_nolgoat/domain/store/StoreRepository.java
- src/main/java/wad/seoul_nolgoat/service/store/StoreService.java
- src/main/java/wad/seoul_nolgoat/util/mapper/StoreMapper.java
- src/main/java/wad/seoul_nolgoat/web/store/StoreController.java
- src/main/java/wad/seoul_nolgoat/web/store/dto/response/StoreListDto.java
- 상점 검색 기능을 구현하였습니다.
- 상점 이름을 통해 상점을 검색하는 기능 구현
- 페이징 적용
- 입력값을 공백을 기준으로 토큰화하여 중복 검색 (최대 두개까지)
close #91
> 상점 검색 기능 구현  

- src/main/java/wad/seoul_nolgoat/auth/oauth2/client/SocialClientService.java
- src/main/java/wad/seoul_nolgoat/auth/oauth2/security/CustomOAuth2UserService.java
- src/main/java/wad/seoul_nolgoat/auth/security/AuthFilter.java
- src/main/java/wad/seoul_nolgoat/auth/security/AuthenticationEntryPointImpl.java
- src/main/java/wad/seoul_nolgoat/config/LogFilterConfig.java
- src/main/java/wad/seoul_nolgoat/exception/GlobalExceptionHandler.java
- src/main/java/wad/seoul_nolgoat/filter/MDCFilter.java
- src/main/java/wad/seoul_nolgoat/filter/RequestLoggingFilter.java
- src/main/java/wad/seoul_nolgoat/service/mail/MailService.java
- src/main/java/wad/seoul_nolgoat/service/search/SearchService.java
- src/main/java/wad/seoul_nolgoat/service/search/sort/SortService.java
- src/main/resources/logback.xml
- 모니터링을 위한 로깅 시스템을 구현했습니다.
- 요청별 로그 추적을 위한 MDC, 로깅 필터 구현
- 로직, 예외 관련 로그 추가
close #97
> 모니터링을 위한 로깅 시스템 구현

- src/main/java/wad/seoul_nolgoat/filter/MDCFilter.java
- 필터의 잘못된 형변환 로직을 수정했습니다.
- 필터의 잘못된 형변환 로직 수정
close #102
> MDC 필터의 잘못된 형변환 로직 수정

- .github/workflows/deploy.yml
- 배포 스크립트에 누락된 설정을 추가했습니다.
- 배포 스크립트 누락된 설정 추가
close #110
> 배포 스크립트 누락된 설정 추가

- .github/workflows/build-test.yml
- .github/workflows/deploy.yml
> [Release] 1차 배포 - 스크립트 수정

- .github/workflows/deploy.yml
- 배포 스크립트에 누락된 백그라운드 실행 설정을 추가했습니다.
- 배포 스크립트 누락된 백그라운드 실행 설정 추가
close #115
> 배포 스크립트 누락된 백그라운드 실행 설정 추가

- .github/workflows/deploy.yml
- 1차 배포 - 누락된 백그라운드 실행 설정 추가
close #
> [Release] 1차 배포 - 누락된 백그라운드 실행 설정 추가

- .github/workflows/deploy.yml
- 무한 대기 문제를 해결하기 위해 배포 스크립트를 수정했습니다.
- 무한 대기 문제 해결을 위한 배포 스크립트 수정
close #118
> 무한 대기 문제 해결을 위한 배포 스크립트 수정

- .github/workflows/deploy.yml
- 1차 배포 - EC2 무한 대기 문제 해결
close #
> [Release] 1차 배포 - EC2 무한 대기 문제 해결

- build.gradle
- src/main/resources/logback.xml
- Logstash 설정을 추가했습니다.
- Logstash 설정 추가
close #121
- ELK 스택 로깅 시스템 구축
> Logstash 설정 추가

- build.gradle
- src/main/resources/logback.xml
- [Release] 1차 배포 - Logstash 설정 추가
close #
> [Release] 1차 배포 - Logstash 설정 추가

- src/main/java/wad/seoul_nolgoat/domain/party/PartyRepositoryCustomImpl.java
- src/main/java/wad/seoul_nolgoat/domain/partyuser/PartyUserRepositoryCustomImpl.java
- QPartyUser import를 올바르게 수정했습니다.
- QPartyUser import 올바르게 수정
close #128
> QPartyUser import 올바르게 수정

- src/main/java/wad/seoul_nolgoat/config/LogFilterConfig.java
- src/main/java/wad/seoul_nolgoat/filter/MdcFilter.java
- MDCFilter를 MdcFilter로 클래스명 수정
- 컨벤션에 맞게 필터 클래스명 수정
close #132
> 컨벤션에 맞게 필터 클래스명 수정

- src/test/java/wad/seoul_nolgoat/service/PartyServiceTest.java
- src/test/resources/data.sql
- 테스트 데이터 수정
- 불필요한 코드 삭제
- 변경된 DTO 스펙을 테스트에 반영
close #141
> 변경된 DTO 스펙을 테스트에 반영

- src/main/resources/logback-prod.xml
- 로그 서버의 탄력적 IP 주소를 설정에 반영
- 로그 서버의 탄력적 IP 주소를 설정에 반영
close #147
> 로그 서버의 탄력적 IP 주소를 설정에 반영

- README.md
- System Architecture 수정
close #151
> System Architecture 수정

- README.md
- src/main/java/wad/seoul_nolgoat/auth/security/AuthFilter.java
- src/main/java/wad/seoul_nolgoat/auth/security/AuthUrlManager.java
- src/main/java/wad/seoul_nolgoat/config/SecurityConfig.java
- src/main/java/wad/seoul_nolgoat/domain/party/PartyRepositoryCustomImpl.java
- src/main/java/wad/seoul_nolgoat/web/party/request/PartySaveDto.java
- src/main/java/wad/seoul_nolgoat/web/party/request/PartyUpdateDto.java
- src/main/resources/logback-prod.xml
- Access 토큰 재발급 요청 URL은 인증이 필요 없도록 설정 수정
- 파티 생성 유효성 검사 기준 및 파티 목록 조회 정렬 방식 수정
- 로그 서버의 탄력적 IP 주소를 설정에 반영
- README 수정
- System Architecture 수정
- ERD 수정
- [Release] 1차 배포 - 최종
close #
> [Release] 1차 배포 - 최종

- src/main/java/wad/seoul_nolgoat/auth/security/AuthFilter.java
- src/main/java/wad/seoul_nolgoat/auth/security/AuthUrlManager.java
- src/main/java/wad/seoul_nolgoat/auth/security/UrlManager.java
- src/main/java/wad/seoul_nolgoat/config/SecurityConfig.java
- src/main/java/wad/seoul_nolgoat/web/comment/CommentController.java
- src/main/java/wad/seoul_nolgoat/web/review/ReviewController.java
- 누락된 Swagger UI 접근 권한 설정을 추가합니다.
- Swagger UI 접근 권한 설정 추가
close #157
> Swagger UI 접근 권한 설정 추가

- src/main/java/wad/seoul_nolgoat/auth/oauth2/dto/GoogleResponse.java
- src/main/java/wad/seoul_nolgoat/auth/oauth2/dto/KakaoResponse.java
- src/main/java/wad/seoul_nolgoat/auth/oauth2/dto/OAuth2Response.java
- src/main/java/wad/seoul_nolgoat/auth/service/AuthService.java
- src/main/java/wad/seoul_nolgoat/auth/web/AuthController.java
- src/main/java/wad/seoul_nolgoat/service/user/UserService.java
- 잘못된 표현 수정 (캐시 → 레디스)
- 유저의 프로필 이미지 정보가 없다면 기본 이미지로 대체
- 코드 정리 및 기능 개선
close #159
> 코드 정리 및 기능 개선

- src/main/java/wad/seoul_nolgoat/auth/oauth2/client/SocialClientService.java
- src/main/java/wad/seoul_nolgoat/auth/oauth2/security/CustomSuccessHandler.java
- src/main/java/wad/seoul_nolgoat/auth/security/AuthFilter.java
- src/main/java/wad/seoul_nolgoat/auth/security/AuthenticationEntryPointImpl.java
- src/main/java/wad/seoul_nolgoat/auth/security/UriManager.java
- src/main/java/wad/seoul_nolgoat/auth/security/UrlManager.java
- src/main/java/wad/seoul_nolgoat/config/SecurityConfig.java
- src/main/java/wad/seoul_nolgoat/exception/ErrorCode.java
- src/main/java/wad/seoul_nolgoat/web/kakaoMap/KakaoMapController.java
- src/main/java/wad/seoul_nolgoat/web/user/UserController.java
- src/test/java/wad/seoul_nolgoat/service/InquiryServiceTest.java
- src/test/java/wad/seoul_nolgoat/service/NoticeServiceTest.java
- UrlManager -> UriManager 이름 변경
- UriManager에 누락된 카카오맵 관련 URI 추가
- 유효하지 않은 요청 URI에 대한 응답 추가
- 카카오맵 관련 URI 관리 및 유효하지 않은 요청 URI에 대한 응답 추가
close #161
> 카카오맵 관련 URI 관리 및 유효하지 않은 요청 URI에 대한 응답 추가

- build.gradle
- src/main/java/wad/seoul_nolgoat/SeoulNolgoatApplication.java
- src/main/java/wad/seoul_nolgoat/domain/party/Party.java
- src/main/java/wad/seoul_nolgoat/domain/party/PartyRepository.java
- src/main/java/wad/seoul_nolgoat/exception/ErrorCode.java
- src/main/java/wad/seoul_nolgoat/exception/GlobalExceptionHandler.java
- src/main/java/wad/seoul_nolgoat/service/party/PartyService.java
- src/test/resources/application-test.yml
- src/test/resources/data.sql
- 파티 엔티티에 version 필드를 추가
- 파티 참여/탈퇴에 재시도 로직 추가
- 관련 처리를 위한 에러 코드 추가 및 핸들러 메서드 구현
close #170
> 비관적 락이 적용된 로직에 낙관적 락을 사용하도록 수정

- src/main/java/wad/seoul_nolgoat/auth/service/AuthService.java
- src/main/java/wad/seoul_nolgoat/auth/web/AuthController.java
- src/main/java/wad/seoul_nolgoat/exception/ErrorCode.java
- 로그아웃, 회원 탈퇴 시 Access 토큰을 블랙리스트 등록하는 로직 삭제
- 요청마다 Access 토큰을 블랙리스트 검증하는 로직 삭제
close #
> Access 토큰 블랙리스트 검증 삭제

- src/main/java/wad/seoul_nolgoat/domain/party/Party.java
- src/main/java/wad/seoul_nolgoat/service/party/PartyService.java
- src/test/java/wad/seoul_nolgoat/service/PartyServiceTest.java
- src/test/resources/data.sql
- 잘못된 동시성 테스트 검증 방식 수정
close #
> 잘못된 동시성 테스트 검증 방식 수정

- src/main/java/wad/seoul_nolgoat/service/search/SearchService.java
- src/main/java/wad/seoul_nolgoat/web/inquiry/dto/request/InquirySaveDto.java
- src/main/java/wad/seoul_nolgoat/web/search/dto/request/SearchConditionDto.java
- 생성자 바인딩 문제 해결을 위해 record를 클래스로 변경
close #
> 생성자 바인딩 문제 해결을 위해 record를 클래스로 변경
